name: Publish LibTextbausteine on Nuget

on:
  push:
    branches: [ main ]

env:
   TEST_PATH: PlcTextbausteine/LibTextbausteine.Test/LibTextbausteine.Test.csproj
   PROJECT_PATH: PlcTextbausteine/PlcTextbausteine.sln
    
jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'


Funktioniert nicht --> in Visual Studio erstellen und manuell laden
