name: Publish LibTextbausteine on Nuget

on:
  push:
    branches: [ main ]

env:
   TEST_PATH: PlcTextbausteine/LibTextbausteine.Test/LibTextbausteine.Test.csproj
   PROJECT_PATH: PlcTextbausteine/LibTextbausteine/LibTextbausteine.csproj
    
jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    
    - name: Test
      run: dotnet test  ${{ env.TEST_PATH }} --verbosity normal
      
    - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release 
    
    - name: Publish LibTextbausteine
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: ${{ env.PROJECT_PATH }}
          NUGET_KEY: ${{secrets.NUGET_TEXTBAUSTEINE_KEY}}
