name: Publish LibTextbausteine on Nuget

on:
  push:
    branches: [ main ]

env:
   TEST_PATH: PlcTextbausteine/LibTextbausteine.Test/LibTextbausteine.Test.csproj
   PROJECT_PATH: PlcTextbausteine/PlcTextbausteine.sln
    
jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
         
- name: Restore dependencies
   run: dotnet restore

- name: Build project
   run: dotnet build --configuration Release --no-restore

- name: Pack project
   run: dotnet pack --configuration Release --no-restore --output ./nupkg

- name: Publish package to NuGet
   env:
     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
   run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
